language: java

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
    
notifications:
  slack:
    rooms:
      - lastweds:N6VmoZVFRHjhDNnIt7MT3jOX#travis-ci
